=== pnp/sp-dev-fx-aces/templates/metadata-schema.json
{
  "$id": "https://developer.microsoft.com/en-us/json-schemas/pnp/samples/v1.0/metadata-schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
      "type": "object",
      "properties": {
          "name": {
              "type": "string",
              "pattern": "pnp-sp-fx-aces-.*"
          },
          "version": {
              "type": "string"
          },
          "source": {
              "type": "string",
              "default": "pnp",
              "pattern": "pnp"
          },
          "title": {
              "type": "string"
          },
          "url": {
              "type": "string",
              "pattern": "https:\/\/github.com\/pnp\/sp-dev-fx-aces\/tree\/main\/(samples|scenarios)\/.*"
          },
          "creationDateTime": {
              "type": "string",
              "format": "date"
          },
          "updateDateTime": {
              "type": "string",
              "format": "date"
          },
          "shortDescription": {
              "type": "string"
          },
          "longDescription": {
              "type": "array",
              "items": {
                  "type": "string"
              }
          },
          "products": {
              "type": "array",
              "items": {
                  "type": "string"
              }
          },
          "categories": {
              "type": "array",
              "items": {
                  "type": "string"
              }
          },
          "metadata": {
              "type": "array",
              "items": {
                  "type": "object",
                  "properties": {
                      "key": {
                          "type": "string"
                      },
                      "value": {
                          "type": "string"
                      }
                  },
                  "required": [
                      "key",
                      "value"
                  ]
              }
          },
          "thumbnails": {
              "type": "array",
              "items": [
                  {
                      "type": "object",
                      "properties": {
                          "type": {
                              "type": "string",
                              "enum": [
                                  "image",
                                  "video",
                                  "slideshow"
                              ]
                          },
                          "order": {
                              "type": "integer"
                          },
                          "alt": {
                              "type": "string"
                          }
                      },
                      "if": {
                          "properties": {
                              "type": {
                                  "const": "slideshow"
                              }
                          }
                      },
                      "then": {
                          "properties": {
                              "slides": {
                                  "type": "array",
                                  "items": {
                                      "type": "object",
                                      "properties": {
                                          "url": {
                                              "type": "string"
                                          },
                                          "order": {
                                              "type": "integer"
                                          },
                                          "alt": {
                                              "type": "string"
                                          }
                                      },
                                      "required": [
                                          "url",
                                          "order",
                                          "alt"
                                      ]
                                  }
                              }
                          },
                          "required": [
                              "slides"
                          ]
                      },
                      "else": {
                          "properties": {
                              "url": {
                                  "type": "string"
                              }
                          },
                          "required": [
                              "url"
                          ]
                      },
                      "required": [
                          "type",
                          "order",
                          "alt"
                      ]
                  }
              ]
          },
          "authors": {
              "type": "array",
              "items": [
                  {
                      "type": "object",
                      "properties": {
                          "gitHubAccount": {
                              "type": "string",
                              "pattern": "^[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*$"
                          },
                          "company": {
                              "type": "string"
                          },
                          "pictureUrl": {
                              "type": "string"
                          }
                      },
                      "required": [
                          "gitHubAccount"
                      ]
                  }
              ]
          },
          "references": {
              "type": "array",
              "items": [
                  {
                      "type": "object",
                      "properties": {
                          "name": {
                              "type": "string"
                          },
                          "description": {
                              "type": "string"
                          },
                          "url": {
                              "type": "string"
                          }
                      },
                      "required": [
                          "name",
                          "url"
                      ]
                  }
              ]
          }
      },
      "required": [
          "name",
          "source",
          "title",
          "url",
          "shortDescription",
          "products",
          "metadata",
          "thumbnails",
          "authors",
          "creationDateTime",
          "updateDateTime"
      ]
  }
}

=== pnp/sp-dev-fx-aces/samples/sample-metadatatemplate.json
[
  {
    "name": "pnp-sp-fx-aces-TODO",
    "source": "pnp",
    "title": "TODO",
    "shortDescription": "TODO",
    "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/TODO",
    "longDescription": [
      "TODO"
    ],
    "creationDateTime": "2021-04-02",
    "updateDateTime": "2021-04-02",
    "products": [
      "SharePoint",
      "Office"
    ],
    "metadata": [
      {
        "key": "CLIENT-SIDE-DEV",
        "value": "React"
      },
      {
        "key": "SPFX-VERSION",
        "value": "1.11.0"
      }
    ],
    "thumbnails": [
      {
        "type": "image",
        "order": 100,
        "url": "https://github.com/pnp/sp-dev-fx-aces/raw/main/samples/TODO",
        "alt": "TODO"
      }
    ],
    "authors": [
      {
        "gitHubAccount": "TODO",
        "pictureUrl": "https://github.com/TODO.png",
        "name": "TODO",
        "twitter": "TODO"
      }
    ],
    "references": [
      {
        "name": "Viva Connections Extensibility guidance",
        "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
        "url": "https://aka.ms/viva/connections/extensibility"
      }
    ]
  }
]

=== pnp/sp-dev-fx-aces/samples/BasicCard-StatusMessage/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-statusmessage",
  "source": "pnp",
  "title": "Teams Status ACE Example",
  "shortDescription": "This ACE demonstrates how to use the Presence Graph API endpoints (beta) to set and retrieve a presence status message for a user.",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/BasicCard-StatusMessage",
  "longDescription": [
    "This ACE demonstrates how to use the Presence Graph API endpoints (beta) to set and retrieve a presence status message for a user."
  ],
  "creationDateTime": "2022-12-21",
  "updateDateTime": "2022-12-21",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.16.0"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/BasicCard-StatusMessage/assets/demo.png",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "yhabersaat",
    "pictureUrl": "https://github.com/yhabersaat.png",
    "name": "Yves Habersaat",
    "twitter": "yhabersaat"
  }],
  "references": [{
      "name": "Viva Connections Extensibility guidance",
      "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
      "url": "https://aka.ms/viva/connections/extensibility"
    },
    {
      "name": "Adaptive Card Documentation",
      "description": "Detailed documentation on Adaptive Cards including the Adaptive Card designer.",
      "url": "https://adaptivecards.io/"
    }, {
      "name": "Adaptive Card Extension Design Guidance",
      "description": "Design guidance for laying out Adaptive Card Extensions.",
      "url": "https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro"
    }
  ]
}]

=== pnp/sp-dev-fx-aces/samples/PrimaryTextCard-FootballStats/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-football-stats",
  "source": "pnp",
  "title": "Football Stats",
  "shortDescription": "This Adaptive Card Extension allows user to choose one of the top five European Football League to get information about current team standing. The data is retrieved using REST API provided by - https://api.football-data.org",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/PrimaryTextCard-FootballStats",
  "longDescription": [
    "This Adaptive Card Extension allows user to choose one of the top five European Football League to get information about current team standing. The data is retrieved using REST API provided by - https://api.football-data.org"
  ],
  "creationDateTime": "2022-01-25",
  "updateDateTime": "2022-01-25",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.13.1"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/PrimaryTextCard-FootballStats/assets/PrimaryTextCard-FootballStatsDemo.gif",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "msoumit",
    "pictureUrl": "https://github.com/msoumit.png",
    "name": "Soumit Mukherjee",
    "twitter": "msoumit"
  }, {
    "gitHubAccount": "XLR8-0",
    "pictureUrl": "https://github.com/XLR8-0.png",
    "name": "Sourav Paul"
  }, {
    "gitHubAccount": "soumyadeep2207",
    "pictureUrl": "https://github.com/soumyadeep2207.png",
    "name": "Soumyadeep Mukherjee"
  }],
  "references": [{
      "name": "Viva Connections Extensibility guidance",
      "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
      "url": "https://aka.ms/viva/connections/extensibility"
    },
    {
      "name": "Adaptive Card Documentation",
      "description": "Detailed documentation on Adaptive Cards including the Adaptive Card designer.",
      "url": "https://adaptivecards.io/"
    }, {
      "name": "Adaptive Card Extension Design Guidance",
      "description": "Design guidance for laying out Adaptive Card Extensions.",
      "url": "https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro"
    }
  ]
}]

=== pnp/sp-dev-fx-aces/samples/PrimaryTextCard-TfL-Status/assets/sample.json
[
  {
    "name": "pnp-sp-fx-aces-ace-londonservices",
    "source": "pnp",
    "title": "Status of London Transport Services",
    "shortDescription": "Adaptive Card displays of London Train services and status",
    "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/PrimaryTextCard-TfL-Status",
    "longDescription": [
      "ACE with multiple card and quick views to display the status of London Train services and allows the user to mark a train line as their favourite with that data using Microsoft Graph."
    ],
    "creationDateTime": "2021-10-06",
    "updateDateTime": "2021-10-06",
    "products": [
      "SharePoint",
      "Viva"
    ],
    "metadata": [
      {
        "key": "CLIENT-SIDE-DEV",
        "value": "React"
      },
      {
        "key": "SPFX-VERSION",
        "value": "1.13.0"
      }
    ],
    "thumbnails": [
      {
        "type": "image",
        "order": 100,
        "url": "https://raw.github.com/pnp/sp-dev-fx-aces/main/samples/PrimaryTextCard-TfL-Status/assets/demo.gif",
        "alt": "London Transport"
      }
    ],
    "authors": [
      {
        "gitHubAccount": "anoopt",
        "company": "Content+Cloud",
        "pictureUrl": "https://github.com/anoopt.png",
        "name": "Anoop Tatti",
        "twitter": "anooptells"
      }
    ],
    "references": [
      {
        "name": "Viva Connections Extensibility guidance",
        "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
        "url": "https://aka.ms/viva/connections/extensibility"
      }
    ]
  }
]

=== pnp/sp-dev-fx-aces/samples/PrimaryTextCard-my-calendar-plan/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-my-calendar",
  "source": "pnp",
  "title": "My Calendar Plan",
  "shortDescription": "This ACE show user events for specific day.",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/PrimaryTextCard-my-calendar-plan",
  "longDescription": [
    "This ACE show user events for specific day."
  ],
  "creationDateTime": "2022-02-25",
  "updateDateTime": "2022-02-25",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.13.1"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/PrimaryTextCard-my-calendar-plan/assets/my-calendar-plan-01.png",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "joaojmendes",
    "pictureUrl": "https://github.com/joaojmendes.png",
    "name": "Jo√£o Mendes"
  }],
  "references": [{
      "name": "Viva Connections Extensibility guidance",
      "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
      "url": "https://aka.ms/viva/connections/extensibility"
    },
    {
      "name": "Adaptive Card Documentation",
      "description": "Detailed documentation on Adaptive Cards including the Adaptive Card designer.",
      "url": "https://adaptivecards.io/"
    }, {
      "name": "Adaptive Card Extension Design Guidance",
      "description": "Design guidance for laying out Adaptive Card Extensions.",
      "url": "https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro"
    }
  ]
}]

=== pnp/sp-dev-fx-aces/samples/PrimaryTextCard-Graph-UnreadEmails/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-graph-unreademails",
  "source": "pnp",
  "title": "Unread Emails Viewer",
  "shortDescription": "Checks the users inbox for unread emails",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/PrimaryTextCard-Graph-UnreadEmails",
  "longDescription": [
    "This Adaptive Card Extension uses the Microsoft Graph to get unread emails in your inbox and displays that as a ACE"
  ],
  "creationDateTime": "2021-12-06",
  "updateDateTime": "2022-05-04",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.14.0"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/PrimaryTextCard-Graph-UnreadEmails/assets/demo.png",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "techienickb",
    "pictureUrl": "https://github.com/techienickb.png",
    "name": "Nick Brown"
  }],
  "references": [{
    "name": "Viva Connections Extensibility guidance",
    "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
    "url": "https://aka.ms/viva/connections/extensibility"
  }]
}]

=== pnp/sp-dev-fx-aces/samples/BasicCard-OneDriveCarousel/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-oneDriveImageOnlyCarousel",
  "source": "pnp",
  "title": "OneDrive Carousel",
  "shortDescription": "This solution provides a carousel that takes images from a OneDrive folder using microsoft graph and ACE and display only the current image.",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/BasicCard-OneDriveCarousel",
  "longDescription": [
    "This solution provides a carousel that takes images from a OneDrive folder using microsoft graph and ACE and display only the current image."
  ],
  "creationDateTime": "2022-04-11",
  "updateDateTime": "2022-04-11",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.13.0"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/BasicCard-OneDriveCarousel/assets/mediumCardView.png",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "GuidoZam",
    "pictureUrl": "https://github.com/GuidoZam.png",
    "name": "Guido Zambarda"
  }],
  "references": [{
      "name": "Viva Connections Extensibility guidance",
      "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
      "url": "https://aka.ms/viva/connections/extensibility"
    },
    {
      "name": "Adaptive Card Documentation",
      "description": "Detailed documentation on Adaptive Cards including the Adaptive Card designer.",
      "url": "https://adaptivecards.io/"
    }, {
      "name": "Adaptive Card Extension Design Guidance",
      "description": "Design guidance for laying out Adaptive Card Extensions.",
      "url": "https://docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro"
    }
  ]
}]

=== pnp/sp-dev-fx-aces/samples/PrimaryTextCard-MyEmails/assets/sample.json
[{
  "name": "pnp-sp-fx-aces-myemails",
  "source": "pnp",
  "title": "My Notifications",
  "shortDescription": "This Adaptive Card Extension shows current users email using Microsoft Graph.",
  "url": "https://github.com/pnp/sp-dev-fx-aces/tree/main/samples/PrimaryTextCard-MyEmails",
  "longDescription": [
    "This sample shows how to build an ACE with a PrimaryText card view and a quick view to display current logged in user's emails."
  ],
  "creationDateTime": "2022-01-03",
  "updateDateTime": "2022-01-03",
  "products": [
    "SharePoint",
    "Viva"
  ],
  "metadata": [{
      "key": "CLIENT-SIDE-DEV",
      "value": "React"
    },
    {
      "key": "SPFX-VERSION",
      "value": "1.13.1"
    }
  ],
  "thumbnails": [{
    "type": "image",
    "order": 100,
    "url": "https://raw.githubusercontent.com/pnp/sp-dev-fx-aces/main/samples/PrimaryTextCard-MyEmails/assets/ace-inaction.gif",
    "alt": "Preview"
  }],
  "authors": [{
    "gitHubAccount": "siddharth-vaghasia",
    "pictureUrl": "https://github.com/siddharth-vaghasia.png",
    "name": "Siddharth Vaghasia"
  }],
  "references": [{
    "name": "Viva Connections Extensibility guidance",
    "description": "Adaptive Card Extensions are client-side components that run in the context of a SharePoint page.",
    "url": "https://aka.ms/viva/connections/extensibility"
  }]
}]
